### ISSUE TITLE
Using the AWS hosted RDS module

### ISSUE THREAD

**Issue by okarlsson** [telia-oss/terraform-aws-rds-instance#21]
### Feature request

Would it be viable to change this module to in turn use the [AWS hosted RDS module](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest?tab=inputs)?

There seems to be more options supported in that module that is not supported by the default `aws_db_instance` resource.

One use case is for enabling storage auto scaling. The default resource only have an `allocated_storage` parameter, while the aws module have `max_allocated_storage`, which will enable storage auto scaling for the instance.

I've gone through the vars that are fed into the resource in this module and they all seem to be supported in the aws module as well with the same name.

**Comment by itsdalmo** [comment]
`max_allocated_storage` is supported by the `aws_db_instance` resource in terraform:
https://registry.terraform.io/providers/hashicorp/aws/2.59.0/docs/resources/db_instance#storage-autoscaling

The module you linked it just that, a module. Its not hosted by AWS and does not have access to any more parameters than is exposed by the `aws_db_instance` resource 😅

**Comment by okarlsson** [comment]
@itsdalmo Noticed that when digging a bit deeper! 

Made a pr #22 that just adds a bunch of parameters not currently available in this module, what do you think?

**Comment by okarlsson** [comment]
Closing this for the added parameters in #22
