### ISSUE TITLE
An argument named "name" is not expected here.

### ISSUE THREAD

**Issue by k1rd3rf** [telia-oss/terraform-aws-rds-instance#31]
### Bug report

> What is the problem?

The `name` field on `aws_rds_instance` is replaced by `db_name`.

### Steps to reproduce

Use the current version of the aws provider. Getting `An argument named "name" is not expected here.`.

### Terraform version

> Run `terraform version` and post the output here:

```bash
$ terraform version

Terraform v1.5.6
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

**Comment by larstobi** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/22668
